### ISSUE TITLE
"Ambiguous implicit values" error when id is a value class

### ISSUE THREAD

**Issue by reactivemaster** [strongtyped/active-slick#81]
When I use simple int or long types for id, then everything is fine. But when I try to use a value class as my model id type, then I get compiler errors.

My code:
```
case class Book(name: String, id: Option[BookId] = None)
case class BookId(value: Int) extends AnyVal with MappedTo[Int]

trait ProfileProvider extends JdbcProfileProvider {
  val dc = DatabaseConfig.forConfig[JdbcProfile]("mydb")
  type JP = JdbcProfile
  val jdbcProfile = dc.driver
  val db = dc.db
}

class BookDAO extends EntityActions with ProfileProvider {
  import jdbcProfile.api._

  val baseTypedType = implicitly[BaseTypedType[Id]]

  type Entity = Book
  type Id = BookId
  type EntityTable = BookTable

  val tableQuery = TableQuery[BookTable]

  def $id(table: BookTable): Rep[Id] = table.id

  val idLens = lens { model: Book => model.id  }
  { (model, id) => model.copy(id = id) }

  class BookTable(tag: Tag) extends Table[Book](tag, "books") {
    def id = column[Id]("id", O.PrimaryKey, O.AutoInc)
    def name = column[String]("name")
    def * = (name, Rep.Some(id)) <> ((Book.apply _).tupled, Book.unapply)
  }

  def findByName(name:String): DBIO[Seq[Book]] = {
    tableQuery.filter(_.name === name).result
  }

  def run[R](dbioAction: DBIOAction[R, NoStream, Nothing]) = db.run(dbioAction)
}
```

Errors are:

```
BookDAO.scala:23: ambiguous implicit values: both value btt in class EntityActions of type => slick.ast.BaseTypedType[BookDAO.this.Id] and method isomorphicType in trait ImplicitColumnTypes of type [A, B](implicit iso: slick.lifted.Isomorphism[A,B], implicit ct: scala.reflect.ClassTag[A], implicit jt: BookDAO.this.jdbcProfile.BaseColumnType[B])BookDAO.this.jdbcProfile.BaseColumnType[A]
match expected type slick.ast.BaseTypedType[BookDAO.this.Id]
val baseTypedType = implicitly[BaseTypedType[Id]]
                                ^
BookDAO.scala:37: ambiguous implicit values:
both value btt in class EntityActions of type => slick.ast.BaseTypedType[BookDAO.this.Id]
and method isomorphicType in trait ImplicitColumnTypes of type [A, B](implicit iso: slick.lifted.Isomorphism[A,B], implicit ct: scala.reflect.ClassTag[A], implicit jt: BookDAO.this.jdbcProfile.BaseColumnType[B])BookDAO.this.jdbcProfile.BaseColumnType[A]
match expected type slick.ast.TypedType[models.BookId]
     def id = column[Id]("id", O.PrimaryKey, O.AutoInc)
                        ^
 two errors found
 (compile:compileIncremental) Compilation failed
```

You can clone my code and check described errors: https://github.com/reactivemaster/active-slick-example/blob/master/app/dao/BookDAO.scala

**Comment by djx314** [comment]
Try
```scala
def id = column[Id]("id", O.PrimaryKey, O.AutoInc)(baseTypedType)
```

**Comment by djx314** [comment]
Can you paste your whole scala file?

**Comment by reactivemaster** [comment]
It doesn't work, because Slick can't figure out how to map BookId to sql type.

**Comment by djx314** [comment]
Why not use `Long` or `Int` replace by `BookId`?

**Comment by reactivemaster** [comment]
Because the value class gives me more benefits of static typing. I will never mix up the identifiers of different models.

Above-described behavior is a bug of the library, not mine, isn't it?

**Comment by djx314** [comment]
Not a bug... Just we won't use it like the code above...

**Comment by rcavalcanti** [comment]
I'm out for holidays and won't have time to look into it now. 

@reactivemaster can you try to create a MappedColumnType for BookId and remove the MappedTo[Int]? The problem may be related to how the mapping is done and to the fact it isn't visible to the compiler where active-slick is expecting it.

**Comment by mkotsbak** [comment]
Another solution that might be better is to use tagged Id datatypes: http://eed3si9n.com/learning-scalaz/Tagged+type.html

See also https://github.com/adamw/macwire#qualifiers

**Comment by reactivemaster** [comment]
> Not a bug... Just we won't use it like the code above...

I think it would be nice to take into account this way of usage.


> can you try to create a MappedColumnType for BookId and remove the MappedTo[Int]

Of course, I can do it, but Slick's "MappedTo" is already provides everything you need for mapping, so why do it manually?

**Comment by rcavalcanti** [comment]
Hi Alexandr,

I wasn't suggesting that you should give up of MappedTo. The idea was to
check if it will work with MappedColumnType. If so, we have already
excluded one possibility.

It will be extremely useful if you can post a small project reproducing
exactly the mapping you are doing. As such we can investigate it further.

Thanks
Em sex, 1 de jul de 2016 às 23:21, Alexandr <notifications@github.com>
escreveu:

**Comment by rcavalcanti** [comment]
HI @reactivemaster,

I finally had sometime to have a look on your sample. 

There is an easy, but verbose, workaround for it. 
In your `BookDao` you have to override the `btt` field.

`EntityActions` there is an implicit defined for BaseTypedType[Id].
```scala
  def baseTypedType: BaseTypedType[Id]

  protected implicit lazy val btt: BaseTypedType[Id] = baseTypedType
```
This is conflicting with the one that is generated by MappedId[_]. I have to investigate further why and how this is happen. Eventually I can reduce some boilerplate.

The workaround is to override the `btt` field and make it non-implicit.
```scala
class BookDAO extends EntityActions with ProfileProvider {
  import jdbcProfile.api._
  val baseTypedType = implicitly[BaseTypedType[Id]]
  override protected lazy val btt: BaseTypedType[Id] = baseTypedType
...
```
As such you will only have one implicit in scope and your code will compile.

**Comment by rcavalcanti** [comment]
FYI, you can simplify your `projection` method as such:
```scala
def * = (name, id.?) <> (Book.tupled, Book.unapply)
```

**Comment by jyotisachdeva57** [comment]
I want to call the procedure tht has five params:
so i have created the function as

```
 def five[T1, T2, T3,T4,T5, R : TypedType](fname: String, fn: Boolean = false): ((Rep[T1], Rep[T2], Rep[T3],Rep[T4],Rep[T5]) => Rep[R]) = {
    val f = SimpleFunction.apply(fname, fn);
    { (t1: Rep[T1], t2: Rep[T2], t3: Rep[T3],t4:Rep[T4],t5:Rep[T5]) => f(Seq(t1, t2, t3,t4,t5)) }
  }
```

My sql procedure function returns TABLE(res1 String, res2 String)

`case class CaseClass(res1: String,res2: String)`

Now i am calling my method:
`
val f =  five[String,String,String,String,String,CaseClass]("function")`

How can i cast the TABLE(res1 String, res2 String) to CaseClass

I have tried:

` implicit val caseClass = CaseClass(r.nextString(), r.nextString())`

It did not work for me.
How do i call val f =  five[String,String,String,String,String,?]("function")` so that the result can be casted to case classs?

**Comment by djx314** [comment]
What's the sql do you want to write? And how do you want to convert the resetset to case class?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JYOTI SACHDEVA"<notifications@github.com&gt;; 
发送时间: 2020年5月18日(星期一) 晚上11:16
收件人: "strongtyped/active-slick"<active-slick@noreply.github.com&gt;; 
抄送: "水山清风"<909134790@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [strongtyped/active-slick] &quot;Ambiguous implicit values&quot; error when id is a value class (#81)





 
I want to call the procedure tht has five params:
 so i have created the function as
  def five[T1, T2, T3,T4,T5, R : TypedType](fname: String, fn: Boolean = false): ((Rep[T1], Rep[T2], Rep[T3],Rep[T4],Rep[T5]) =&gt; Rep[R]) = {     val f = SimpleFunction.apply(fname, fn);     { (t1: Rep[T1], t2: Rep[T2], t3: Rep[T3],t4:Rep[T4],t5:Rep[T5]) =&gt; f(Seq(t1, t2, t3,t4,t5)) }   }  
My sql procedure function returns TABLE(res1 String, res2 String)
 
case class CaseClass(res1: String,res2: String)
 
Now i am calling my method:
  val f =  five[String,String,String,String,String,CaseClass]("function")
 
How can i cast the TABLE(res1 String, res2 String) to CaseClass
 
I have tried:
 
 implicit val caseClass = CaseClass(r.nextString(), r.nextString())
 
It did not work for me.
 How do i call val f =  fiveString,String,String,String,String,?` so that the result can be casted to case classs?
